# --- !Ups
CREATE TABLE ISSUE (
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ID_KEY INT NOT NULL,
  ISSUE_KEY VARCHAR(64) NOT NULL,
  SUMMARY VARCHAR(512) NOT NULL,
  POINT FLOAT
);

# --- !Downs
DROP TABLE ISSUE;
